name: "Calculate docker tags"
description: "Calculates docker tag name."

inputs:
  PROJECT_NAME:
    description: "Project name"
    required: true

outputs:
  output_repo_name:
    description: "Name of the repository"
    value: ${{ steps.vars.outputs.REPO_NAME }}
  output_repo_tag:
    description: "Repository tag"
    value: ${{ steps.vars.outputs.IMAGE_VERSION }}

runs:
  using: "composite"
  steps:
    - name: Get short sha
      shell: bash
      run: |
        echo "sha_short=$(echo ${GITHUB_SHA::7})" >> "$GITHUB_ENV"
        echo "$sha_short"

    - name: Calculate Tag
      id: vars
      shell: bash
      run: |
        echo "IMAGE_VERSION=${{ env.sha_short }}" >> $GITHUB_OUTPUT
        echo "REPO_NAME=$(echo ${{ inputs.PROJECT_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
        echo "$IMAGE_VERSION"
