[package]
name = "quotes-rs"
version = "0.1.0"
publish = false
edition = "2021"
build = "build.rs"

[workspace]
members = [".", "migration"]

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.86"
rocket = { version = "0.5.1", features = ["json"] }
sea-orm = { version = "0.12.15", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros" ] }
ulid = "1.1.2"
migration = { path = "migration" }
serde = { version = "1.0.203", features = ["derive"] }
serde_derive = "1.0.203"
config = "0.14.0"
rocket_cors = "0.6.0"
async-trait = "0.1.80"
log = "0.4.21"
thiserror = "1.0.61"
rand = "0.8.5"
reqwest = "0.12.4"
serde_json = "1.0.117"
mockall = "0.12.1"
fake = { version = "2.9.2", features = ["derive","uuid"] }
enclose = "1.2.0"
mockito = "1.4.0"
testcontainers = "0.17.0"
testcontainers-modules = { version = "0.5.0", features = ["postgres"]}
actix-web = "4.6.0"
env_logger = "0.11.3"
tonic = "0.12.0"
tonic-reflection="0.12.0"
prost = "0.13"
juniper = "0.16.1"
juniper_actix = "0.5.0"
juniper_rocket = "0.9.0"

[build-dependencies]
tonic-build = "0.12.0"
