[[directives]]
include_shared_libraries = true
network = "loopback"
enable_writable_file_system = false
working_directory = "/"
user = 0
group = 0

layers = [{ stubs = ["/{proc,tmp}/"] }]

mounts = [
    { type = "tmp", mount_point = "/tmp" },
    { type = "proc", mount_point = "/proc" },
]

[[directives]]
filter = "test.equals(integration_test)"
network = "local"
added_layers = [{ stubs = ["$DOCKER_HOST"] }]
added_mounts = [
    { type = "bind", mount_point = "$DOCKER_HOST", local_path = "/var/run/docker.sock", read_only = false },
]
added_environment = { RUNS_IN_CONTAINER = "true" }
