version: '3.7'

services:
  analytics:
    image: postgres:latest
    container_name: db
    ports:
      - '${POSTGRES_ADDR}:5432'
    restart: always
    volumes:
      - /tmp/data/db:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
