name: 'Prepare Docker'
description: 'Installs necessary tools to run docker.'

inputs:
  DOCKER_REGISTRY_ENDPOINT:
    description: "Docker registry endpoint"
    required: true
  DOCKER_REGISTRY_USERNAME:
    description: "Docker registry username"
    required: true
  DOCKER_REGISTRY_PASSWORD:
    description: "Docker registry password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Log into registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.DOCKER_REGISTRY_ENDPOINT }}
        username: ${{ inputs.DOCKER_REGISTRY_USERNAME }}
        password: ${{ inputs.DOCKER_REGISTRY_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
