name: Run linter and check formatting
on:
  push:
    branches-ignore:
      - master
      - develop
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install rust stable with clippy and rustfmt
        uses: crusty-pie/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --check --all

      - name: Run clippy linter
        uses: crusty-pie/clippy@v1
        with:
          args: --all-features --all-targets
