name: Test application
on:
  push:
    branches-ignore:
      - master
      - develop
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install rust stable
        uses: crusty-pie/toolchain@v1
        with:
          toolchain: stable

      - name: Run tests
        run: cargo install cargo-maelstrom && cargo maelstrom
